# Generated by Django 5.0.6 on 2024-06-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='idade',
            field=models.IntegerField(default=False),
        ),
    ]
