# Generated by Django 5.0.6 on 2024-06-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_casa_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='profissao',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='casa',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
    ]
