# Generated by Django 5.0.6 on 2024-06-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_casa_profissao_alter_casa_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='casa',
            name='empresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.empresa'),
        ),
    ]
