# Generated by Django 5.0.6 on 2024-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=1000)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=30)),
                ('data', models.DateField()),
            ],
        ),
    ]
