# Generated by Django 5.0.6 on 2024-07-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0004_alter_categoria_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
