# Generated by Django 5.0.6 on 2024-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0005_alter_categoria_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='organizador',
            options={'ordering': ['id'], 'verbose_name': 'Organizador', 'verbose_name_plural': 'Organizadores'},
        ),
        migrations.AlterField(
            model_name='organizador',
            name='ddd',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
