# Generated by Django 5.0.6 on 2024-07-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0006_alter_categoria_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
