# Generated by Django 5.0.6 on 2024-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0008_alter_organizador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='nick',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
