# Generated by Django 5.0.6 on 2024-07-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0009_organizador_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='organizador',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Organizador',
        ),
    ]
