# Generated by Django 5.0.6 on 2024-07-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto_eventos', '0010_remove_evento_categoria_remove_evento_organizador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(default='', max_length=1000)),
                ('ativo_inativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('ddd', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=15)),
                ('nick', models.CharField(blank=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=1000)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('imagem', models.ImageField(upload_to='eventos_imagens/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projeto_eventos.categoria')),
                ('organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projeto_eventos.organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data'],
            },
        ),
    ]
