# Generated by Django 5.0.6 on 2024-07-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(null=True, upload_to='eventos_imagens/'),
        ),
    ]
