# Generated by Django 5.0.6 on 2024-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0012_alter_evento_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='ativo_inativo',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='bairro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cidade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_imagens/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='pais',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='evento',
            name='rua',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='ddd',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
