# Generated by Django 5.0.6 on 2024-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0013_alter_categoria_ativo_inativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
