# Generated by Django 5.0.6 on 2024-07-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0015_alter_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='bairro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
