# Generated by Django 5.0.6 on 2024-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0016_alter_evento_bairro_alter_evento_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagem_pics/'),
        ),
    ]
