# Generated by Django 5.0.6 on 2024-07-07 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0018_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
