# Generated by Django 5.0.6 on 2024-07-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0022_evento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='organizador',
        ),
    ]
