# Generated by Django 5.0.6 on 2024-07-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos', '0023_remove_evento_organizador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizador',
        ),
    ]
