# Generated by Django 5.0.6 on 2024-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_casa_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
