# Generated by Django 5.0.6 on 2024-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_empresa_casa_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='registro',
            field=models.CharField(max_length=200),
        ),
    ]
