# Generated by Django 5.0.6 on 2024-06-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_empresa_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='casa',
            name='profissao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.profissao'),
        ),
    ]
