# Generated by Django 5.0.7 on 2024-07-21 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_pagina_link1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casa",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="casa",
            name="profissao",
        ),
        migrations.DeleteModel(
            name="Pagina",
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=200, verbose_name="Escolha"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.question",
                verbose_name="Selecione a Pergunta",
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="votes",
            field=models.IntegerField(default=0, verbose_name="Quantidade de votos"),
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateTimeField(verbose_name="Data / Horário de criação"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=200, verbose_name="Pergunta"),
        ),
        migrations.DeleteModel(
            name="Empresa",
        ),
        migrations.DeleteModel(
            name="Casa",
        ),
        migrations.DeleteModel(
            name="Profissao",
        ),
    ]
